# Generated by Django 4.2.9 on 2024-01-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='name',
            new_name='names',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=8),
            preserve_default=False,
        ),
    ]
